name: Tests

on:
  pull_request:
    branches-ignore:
      - master
  push:
    branches:
      - xelon/master

permissions:
  contents: read

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout
        uses: actions/checkout@v4
